In [20]:
import numpy as np

#Criando
arr15 = np.arange(1, 16)
print(arr15)


#Soma
sum = np.sum(arr15)
print(sum)

soma_acumulada = np.cumsum(arr15)
print(soma_acumulada)

#subtração
sub = np.subtract(arr15, 1)
print(sub)

# divisao
div = np.divide(arr15, 2)
print(div)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
120
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]


In [11]:
arr16 = np.array([3,2,1])
arr17 = np.array([1,2,3])

arr18 = np.add(arr16, arr17)
print(arr18)


#multplicação
arr19 = np.array([[1,2],[3,4]])
arr20 = np.array([[5,6],[7,8]])
print(arr19.shape, arr20.shape)

arr21 = np.dot(arr19, arr20)
print(f"Multiplicando \n{arr19} x \n{arr20}\n Resultado =  {arr21}")

[4 4 4]
(2, 2) (2, 2)
Multiplicando 
[[1 2]
 [3 4]] x 
[[5 6]
 [7 8]]
 Resultado =  [[19 22]
 [43 50]]


In [15]:
arr22 = np.diag(np.arange(3))

print("Matiz ",arr22)

#Fatiamento
print(arr22[1,1])

print(arr22[1])



print(arr22[:,2])

Matiz  [[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]
1
[0 1 0 0 0 0 0 0 0 0]
[0 0 2 0 0 0 0 0 0 0]


In [19]:
arr23 = np.arange(10)

print(arr23[2:9:3])

a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
 
print(a == b)

print(np.array_equal(a,b))


[2 5 8]
[False  True False  True]
False
